package constant

var (
	RESPONSE_MESSAGE_SUCCESS                    = "Success"
	RESPONSE_MESSAGE_INVALID_BODY_REQ           = "Invalid Body Request"
	RESPONSE_MESSAGE_INVALID_HEADER_REQ         = "Invalid Header Request"
	RESPONSE_MESSAGE_INVALID_QUERY_PARAMS       = "Invalid Query Parameters"
	RESPONSE_MESSAGE_BODY_REQ_EMPTY             = "Body Request Empty"
	RESPONSE_MESSAGE_INVALID_DATA_TYPE          = "Invalid Data Type"
	RESPONSE_MESSAGE_INVALID_DATE_FORMAT        = "Invalid Date Format"
	RESPONSE_MESSAGE_INVALID_TIME_FORMAT        = "Invalid Time Format"
	RESPONSE_MESSAGE_INVALID_AUTH_TOKEN         = "Invalid Auth Token"
	RESPONSE_MESSAGE_INVALID_DATA_ALREADY_EXIST = "Data Already Exist"
	RESPONSE_MESSAGE_AUTH_TOKEN_EXPIRED         = "Auth Token Expired"
	RESPONSE_MESSAGE_AUTH_TOKEN_EMPTY           = "Auth Token Empty"
	RESPONSE_MESSAGE_FORBIDDEN_ACCESS           = "Forbidden Access"
	RESPONSE_MESSAGE_DATA_NOT_FOUND             = "Data Not Found"
	RESPONSE_MESSAGE_ROUTE_NOT_FOUND            = "Route Not Found"
	RESPONSE_MESSAGE_DATABASE_ERROR             = "Database Error"
	RESPONSE_MESSAGE_SERVICE_ERROR              = "Service Error"
	RESPONSE_MESSAGE_EXTERNAL_SERVICE_ERROR     = "External Service Error"
	RESPONSE_MESSAGE_PRODUCE_MESSAGE_ERROR      = "Failed to produce message"
	RESPONSE_MESSAGE_TIMEOUT                    = "Timeout"
	RESPONSE_MESSAGE_UNDEFINED_ERROR            = "Undefined Error"
	RESPONSE_MESSAGE_GENERAL_ERROR              = "General Error"
)
