package constant

var (
	RESPONSE_CODE_SUCCESS        = "00"
	RESPONSE_CODE_BAD_REQUEST    = "01"
	RESPONSE_CODE_AUTH_ERROR     = "02"
	RESPONSE_CODE_NOT_FOUND      = "03"
	RESPONSE_CODE_INTERNAL_ERROR = "05"
)
